server:
  port: 8080

spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql:///hawdee?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.hawdee.demo.entity
logging:
  level:
    org:
      springframework:
        security=info:
#showSql
